export SMTP_SERVER="smtp.163.com"
export SMTP_PORT=465
export SMTP_USE_SSL=true
export SMTP_SENDER_EMAIL="mrnobody212377@163.com"

echo "SMTP_SERVER: $SMTP_SERVER"
echo "SMTP_PORT: $SMTP_PORT"
echo "SMTP_USE_SSL: $SMTP_USE_SSL"
echo "SMTP_SENDER_EMAIL: $SMTP_SENDER_EMAIL"
echo "SMTP_SENDER_PASSWORD: $SMTP_SENDER_PASSWORD"